site_name: hirano-lab-wiki
site_description: 平野研究室の公開サイト
repo_url: https://github.com/shingohirano-astro/lab-wiki-public
repo_name: lab-wiki-public
edit_uri: edit/main/docs/public/

theme:
  name: material
  language: ja
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

docs_dir: docs/public
site_dir: site

nav:
  - ホーム: README.md
  - ニュース: news.md
  - 研究紹介: research_overview.md
  - メンバー: members.md
  - スケジュール: schedule.md
